version: "2.4"

services:
  api:
    build: .
    image: recommender
    container_name: api
    command: [
      "recommender-api",
      "--user=nobody",
      "--api-address=0.0.0.0",
      "--api-port=8080",
      "--pg-url=postgresql://postgres:hackme@postgresql:5432/recommender",
      "--redis-url=redis://:hackme@redis:6379/0",
    ]
    restart: always
    ports:
      - 8080:8080
    depends_on:
      redis:
        condition: service_healthy
      postgresql:
        condition: service_healthy

  db-migration:
    build: .
    image: recommender
    container_name: db-migration
    command: bash -c "recommender-db upgrade head && recommender-data && recommender-cache"
    environment:
      - RECOMMENDER_PG_URL=postgresql://postgres:hackme@postgresql:5432/recommender
      - RECOMMENDER_REDIS_URL=redis://:hackme@redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
      postgresql:
        condition: service_healthy

  redis:
    image: bitnami/redis:5.0.9
    container_name: redis
    restart: always
    environment:
      - REDIS_PASSWORD=hackme
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 2s
      retries: 10

  postgresql:
    image: bitnami/postgresql:11.8.0
    container_name: postgresql
    restart: always
    environment:
      - POSTGRESQL_PASSWORD=hackme
      - POSTGRESQL_DATABASE=recommender
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "recommender" ]
      interval: 5s
      timeout: 2s
      retries: 10
